import type { Metadata } from "next";
import "./globals.css";
import { inter, openSans } from "./fonts";
import { RevealOnScroll } from "@/components/shared/RevealOnScroll";
import SmoothScroll from "@/components/shared/SmoothScroll";
import Header from "@/components/shared/Header";
// import Header from "@/components/shared/Header";
// import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${openSans.variable} antialiased`}>
        <SmoothScroll>
          <RevealOnScroll />
          <Header />
          {children}
          {/* <Footer /> */}
        </SmoothScroll>
      </body>
    </html>
  );
}
